//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSUNTO_SUPORTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSUNTO_SUPORTE()
        {
            this.HISTORICO_SUPORTE_ITENS = new HashSet<HISTORICO_SUPORTE_ITENS>();
        }
    
        public long ID { get; set; }
        public long ID_CATEGORIA { get; set; }
        public long ID_USUARIO { get; set; }
        public string DESCRICAO { get; set; }
        public string LINK_MANUAL { get; set; }
        public string LINK_VIDEO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    
        public virtual CATEGORIA_SUPORTE CATEGORIA_SUPORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_SUPORTE_ITENS> HISTORICO_SUPORTE_ITENS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
