//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PROJETO
    {
        public long ID { get; set; }
        public long ID_USUARIO { get; set; }
        public Nullable<long> ID_PROJETO { get; set; }
    
        public virtual PROJETO PROJETO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
