//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.EMAIL_CLIENTE = new HashSet<EMAIL_CLIENTE>();
            this.HISTORICO_SUPORTE = new HashSet<HISTORICO_SUPORTE>();
            this.TELEFONE_CLIENTE = new HashSet<TELEFONE_CLIENTE>();
        }
    
        public long ID { get; set; }
        public long ID_PROJETO { get; set; }
        public string RAZAOSOCIAL { get; set; }
        public string CPFCNPJ { get; set; }
        public string NOME_FANTASIA { get; set; }
        public string EMAIL { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string CEP { get; set; }
        public string CONTATO { get; set; }
    
        public virtual PROJETO PROJETO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_CLIENTE> EMAIL_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_SUPORTE> HISTORICO_SUPORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEFONE_CLIENTE> TELEFONE_CLIENTE { get; set; }
    }
}
