//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONTROLEEEntities : DbContext
    {
        public CONTROLEEEntities()
            : base("name=CONTROLEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASSUNTO_SUPORTE> ASSUNTO_SUPORTE { get; set; }
        public virtual DbSet<CATEGORIA_SUPORTE> CATEGORIA_SUPORTE { get; set; }
        public virtual DbSet<EMAIL_CLIENTE> EMAIL_CLIENTE { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<HISTORICO_SUPORTE> HISTORICO_SUPORTE { get; set; }
        public virtual DbSet<HISTORICO_SUPORTE_ITENS> HISTORICO_SUPORTE_ITENS { get; set; }
        public virtual DbSet<PROJETO> PROJETO { get; set; }
        public virtual DbSet<TELEFONE_CLIENTE> TELEFONE_CLIENTE { get; set; }
        public virtual DbSet<USUARIO_PROJETO> USUARIO_PROJETO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
