//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_SUPORTE_ITENS
    {
        public long ID { get; set; }
        public long ID_HISTORICO_SUPORTE { get; set; }
        public long ID_ASSUNTO_SUPORTE { get; set; }
        public long ID_USUARIO { get; set; }
        public string NOME_CLIENTE { get; set; }
        public string CLINICA_CLIENTE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string OBSERVACAO { get; set; }
        public long ID_CATEGORIA_SUPORTE { get; set; }

        public virtual ASSUNTO_SUPORTE ASSUNTO_SUPORTE { get; set; }
        public virtual CATEGORIA_SUPORTE CATEGORIA_SUPORTE { get; set; }
        public virtual HISTORICO_SUPORTE HISTORICO_SUPORTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
