//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ASSUNTO_SUPORTE = new HashSet<ASSUNTO_SUPORTE>();
            this.HISTORICO_SUPORTE_ITENS = new HashSet<HISTORICO_SUPORTE_ITENS>();
            this.USUARIO_PROJETO = new HashSet<USUARIO_PROJETO>();
        }
    
        public long ID { get; set; }
        public long ID_EMPRESA { get; set; }
        public long ID_GRUPO { get; set; }
        public string LOGINN { get; set; }
        public string SENHA { get; set; }
        public bool SUPERVISOR { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSUNTO_SUPORTE> ASSUNTO_SUPORTE { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_SUPORTE_ITENS> HISTORICO_SUPORTE_ITENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PROJETO> USUARIO_PROJETO { get; set; }
    }
}
